version: '2'
services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - db:db
    environment:
      - RAILS_ENV=development
    extends: 
      file: ./config/mariadb.yml
      service: password
    depends_on:
      - db
  db:
    image: mariadb:10.2.12
    ports:
      - "3306:3306"
    volumes:
      - ./data/volumes:/var/lib/mysql
    extends:
      file: ./config/mariadb.yml
      service: password
