development:
  clients:
    default:
      database: favobase_development
      hosts:
        - <%= ENV['DB_PORT_27017_TCP_ADDR'] %>:27017
      options:
  options:
test:
  clients:
    default:
      database: favobase_test
      hosts:
        - <%= ENV['DB_PORT_27017_TCP_ADDR'] %>:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
